"""
model_pymc.py — Bayesian Linear Regression with PyMC + MCMC Sampling

Model Specification:
    cnt_i ~ N(mu_i, sigma^2)
    mu_i  = beta0 + beta1 * temp_i + beta2 * hum_i
    i = 1, ..., 360

Sampler: NUTS (PyMC Default, No-U-Turn Sampler)
    - 4 chains × (1000 tune + 2000 draws) = 8000 posterior samples
    - Tune phase serves as warm-up and burn-in, discarded after automatic step size tuning
    - random_seed=42 ensures reproducibility

Input: data/day_subsampled.csv (from Module A)
Output:
    results/trace.nc                       # Posterior samples (for Modules C/D)
    results/figures/prior_predictive.png   # Prior predictive check plot
"""

from __future__ import annotations

import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm

from src.config import (
    DATA_DIR,
    FIGURES_DIR,
    FEATURES,
    N_CHAINS,
    N_DRAWS,
    N_TUNE,
    POSTERIOR_TABLE_FILE,  # noqa: F401  (Unused in this file, for IDE navigation)
    RANDOM_SEED,
    RESULTS_DIR,
    SUBSAMPLED_FILE,
    TARGET,
    TARGET_ACCEPT,
    TRACE_FILE,
    setup_logging,
)
from src.priors import define_priors, prior_summary


# Data Loading
def load_data() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Read cnt, temp, hum columns from day_subsampled.csv generated by Yue.

    Returns
    -------
    cnt : np.ndarray, shape (360,)
    temp: np.ndarray, shape (360,)
    hum : np.ndarray, shape (360,)
    """
    csv_path = DATA_DIR / SUBSAMPLED_FILE
    if not csv_path.exists():
        raise FileNotFoundError(
            f"{csv_path} not found.\n"
            "Please copy day_subsampled.csv from Yue's project to the data/ directory."
        )
    df = pd.read_csv(csv_path)
    return (
        df[TARGET].to_numpy(),
        df[FEATURES[0]].to_numpy(),
        df[FEATURES[1]].to_numpy(),
    )


# Model Construction
def build_model(
    cnt: np.ndarray, temp: np.ndarray, hum: np.ndarray
) -> pm.Model:
    """
    Build PyMC model object (priors + likelihood) without sampling.

    Parameters
    ----------
    cnt, temp, hum : 360-dimensional arrays from day_subsampled.csv
    """
    with pm.Model() as model:
        # Priors (imported from priors.py)
        priors = define_priors()

        # Linear predictor mu_i = beta0 + beta1 * temp_i + beta2 * hum_i
        mu = (
            priors["beta0"]
            + priors["beta1"] * temp
            + priors["beta2"] * hum
        )

        # Likelihood cnt_i ~ N(mu_i, sigma^2)
        # observed=cnt passes data to PyMC for automatic likelihood calculation
        pm.Normal("cnt_obs", mu=mu, sigma=priors["sigma"], observed=cnt)

    return model


# Prior Predictive Check
def run_prior_predictive(model: pm.Model, save_path) -> None:
    """
    Sample 500 synthetic datasets from the prior predictive distribution and plot the distribution.

    Purpose: Validate if priors are "reasonably wide" before seeing data —
    If prior predictive distribution is much narrower than the actual cnt range → priors are too tight;
    If it extends to extreme values → acceptable, as weakly informative priors allow this.
    """
    with model:
        prior_pred = pm.sample_prior_predictive(
            samples=500, random_seed=RANDOM_SEED
        )

    samples = prior_pred.prior_predictive["cnt_obs"].values.flatten()

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(
        samples, bins=80, density=True, alpha=0.6,
        edgecolor="black", label="Prior predictive draws",
    )
    ax.axvline(0, color="red", linestyle="--", label="cnt = 0")
    ax.axvline(8555, color="green", linestyle="--", label="Observed max cnt")
    ax.set_xlabel("Simulated cnt")
    ax.set_ylabel("Density")
    ax.set_title("Prior Predictive Distribution (n=500)")
    ax.legend()
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# MCMC Sampling
def run_mcmc(model: pm.Model) -> az.InferenceData:
    """
    Run NUTS sampling on the pre-built PyMC model.

    Returns ArviZ InferenceData object, which can be saved directly as a .nc file.
    """
    with model:
        idata = pm.sample(
            draws=N_DRAWS,
            tune=N_TUNE,
            chains=N_CHAINS,
            target_accept=TARGET_ACCEPT,
            random_seed=RANDOM_SEED,
            return_inferencedata=True,
            progressbar=True,
        )
    return idata


# Main Workflow
def main() -> None:
    """Full pipeline: Load data → Build model → Prior predictive check → MCMC → Save trace.nc"""
    logger = setup_logging()

    logger.info("=== Module B: Bayesian Inference ===")
    logger.info("Prior specification:\n%s", prior_summary())

    logger.info("Loading subsampled data")
    cnt, temp, hum = load_data()
    logger.info(
        "Data loaded: n=%d, mean(cnt)=%.1f, sd(cnt)=%.1f",
        len(cnt), cnt.mean(), cnt.std(),
    )

    logger.info("Building PyMC model")
    model = build_model(cnt, temp, hum)

    logger.info("Running prior predictive check (500 samples)")
    run_prior_predictive(model, FIGURES_DIR / "prior_predictive.png")

    logger.info(
        "Running NUTS sampling: %d chains × (%d tune + %d draws)",
        N_CHAINS, N_TUNE, N_DRAWS,
    )
    idata = run_mcmc(model)

    trace_path = RESULTS_DIR / TRACE_FILE
    idata.to_netcdf(trace_path)
    logger.info("Saved trace to %s", trace_path)

    # Print concise summary
    summary = az.summary(
        idata,
        var_names=["beta0", "beta1", "beta2", "sigma"],
        hdi_prob=0.95,
    )
    logger.info("Quick posterior summary:\n%s", summary.to_string())

    logger.info("Done. Run posterior_summary.py next.")


if __name__ == "__main__":
    main()
