"""
posterior_summary.py — Posterior Summary Table + Posterior Density Plots + Forest Plot

Load trace.nc and generate outputs:
  results/posterior_table.csv          # Posterior summary (mean/sd/95% CrI/ESS/R-hat)
  results/figures/posterior_density.png # Marginal posterior densities for 4 parameters
  results/figures/posterior_forest.png  # Forest plot: clear visualization of credible intervals

Follows the field naming contract from Module A's frequentist_results.csv:
    parameter ∈ {beta_0, beta_1_temp, beta_2_hum, sigma}
Enables direct merging for integration by Student D.
"""

from __future__ import annotations

import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.config import (
    FIGURES_DIR,
    POSTERIOR_TABLE_FILE,
    RESULTS_DIR,
    TRACE_FILE,
    setup_logging,
)


# Load Trace
def load_trace() -> az.InferenceData:
    """Load the trace.nc file generated by model_pymc.py."""
    trace_path = RESULTS_DIR / TRACE_FILE
    if not trace_path.exists():
        raise FileNotFoundError(
            f"{trace_path} not found. Please run `python -m src.model_pymc` first."
        )
    return az.from_netcdf(trace_path)


# Summary Table
def build_summary_table(idata: az.InferenceData) -> pd.DataFrame:
    """
    Generate a posterior summary table compliant with Module A's data contract.

    Columns: parameter, post_mean, post_sd, ci_lower, ci_upper, ess_bulk, r_hat
    Parameter names: beta_0, beta_1_temp, beta_2_hum, sigma (fully aligned with A)
    """
    var_names = ["beta0", "beta1", "beta2", "sigma"]
    parameter_aliases = ["beta_0", "beta_1_temp", "beta_2_hum", "sigma"]

    summary = az.summary(
        idata,
        var_names=var_names,
        hdi_prob=0.95,
        kind="all",
    )

    # Note: HDI column names vary across ArviZ versions
    # Possible names: "hdi_2.5%" / "hdi_97.5%" or "hdi_lower" / "hdi_upper"
    hdi_lower_col = next(c for c in summary.columns if "hdi" in c and ("2.5" in c or "lower" in c))
    hdi_upper_col = next(c for c in summary.columns if "hdi" in c and ("97.5" in c or "upper" in c))

    df = pd.DataFrame({
        "parameter": parameter_aliases,
        "post_mean": summary["mean"].values,
        "post_sd":   summary["sd"].values,
        "ci_lower":  summary[hdi_lower_col].values,
        "ci_upper":  summary[hdi_upper_col].values,
        "ess_bulk":  summary["ess_bulk"].values,
        "r_hat":     summary["r_hat"].values,
    })
    return df


# Posterior Density Plot
# Soft, high-contrast color scheme for 4 parameters
PARAM_COLORS = {
    "beta0": "#2E86AB",   # Ocean blue
    "beta1": "#E07A5F",   # Brick red
    "beta2": "#81B29A",   # Mint green
    "sigma": "#9D4EDD",   # Purple
}
PARAM_LABELS = {
    "beta0": r"$\beta_0$ (intercept)",
    "beta1": r"$\beta_1$ (temp)",
    "beta2": r"$\beta_2$ (hum)",
    "sigma": r"$\sigma$",
}


def plot_posterior_density(idata: az.InferenceData, save_path) -> None:
    """Plot marginal posterior densities for 4 parameters (2x2 subplots) with custom colors."""
    var_names = list(PARAM_COLORS.keys())

    fig, axes = plt.subplots(2, 2, figsize=(13, 8.5), facecolor="white")
    axes_flat = axes.flatten()

    for ax, var in zip(axes_flat, var_names):
        az.plot_posterior(
            idata,
            var_names=[var],
            hdi_prob=0.95,
            ax=ax,
            color=PARAM_COLORS[var],
            point_estimate="mean",
            textsize=11,
        )
        # Replace variable name with user-friendly title
        ax.set_title(PARAM_LABELS[var], fontsize=13, weight="bold")
        # Add subtle grid lines
        ax.grid(axis="x", alpha=0.2, linestyle="--")
        ax.set_facecolor("#FAFAFA")

    fig.suptitle(
        "Posterior Distributions of Parameters",
        fontsize=15, weight="bold", y=1.00,
    )
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def plot_posterior_forest(idata: az.InferenceData, save_path) -> None:
    """
    Custom forest plot: 95% Credible Intervals for 4 parameters.
    Each parameter displays:
      - Thick blue line: 95% HDI interval
      - White dot: posterior mean
      - Three red dashed lines: lower / mean / upper values extending to the x-axis
      - Numeric labels above each interval
    """
    var_names = list(PARAM_COLORS.keys())

    summary = az.summary(idata, var_names=var_names, hdi_prob=0.95)
    hdi_lower_col = next(
        c for c in summary.columns if "hdi" in c and ("2.5" in c or "lower" in c)
    )
    hdi_upper_col = next(
        c for c in summary.columns if "hdi" in c and ("97.5" in c or "upper" in c)
    )

    means = summary["mean"].values
    lowers = summary[hdi_lower_col].values
    uppers = summary[hdi_upper_col].values

    fig, ax = plt.subplots(figsize=(13, 6.5), facecolor="white")

    n = len(var_names)
    y_positions = np.arange(n)[::-1]   # Display first parameter at the top

    # Vertical baseline for dashed red lines (data coordinates)
    y_baseline = -0.6

    for y, var, mean, lower, upper in zip(
        y_positions, var_names, means, lowers, uppers
    ):
        bar_color = PARAM_COLORS[var]

        # HDI interval (thick solid line)
        ax.plot(
            [lower, upper], [y, y],
            color=bar_color, linewidth=6,
            solid_capstyle="round", zorder=3,
        )

        # Three red dashed lines: lower / mean / upper extending to y_baseline
        for x_val in [lower, mean, upper]:
            ax.plot(
                [x_val, x_val], [y, y_baseline],
                color="red", linestyle="--", linewidth=1.2,
                alpha=0.55, zorder=2,
            )

        # Numeric labels (above intervals)
        # Offset sigma labels to avoid overlap (narrow CrI: 1393-1610)
        if var == "sigma":
            ax.text(lower - 120, y + 0.18, f"{lower:.0f}",
                    ha="right", va="bottom", fontsize=10, color="red")
            ax.text(upper + 120, y + 0.18, f"{upper:.0f}",
                    ha="left", va="bottom", fontsize=10, color="red")
        else:
            ax.text(lower, y + 0.18, f"{lower:.0f}",
                    ha="center", va="bottom", fontsize=10, color="red")
            ax.text(upper, y + 0.18, f"{upper:.0f}",
                    ha="center", va="bottom", fontsize=10, color="red")
        ax.text(mean, y + 0.30, f"mean = {mean:.0f}",
                ha="center", va="bottom", fontsize=11, color="black", weight="bold")

        # Posterior mean marker (white-filled circle)
        ax.scatter(
            mean, y, s=140,
            facecolor="white", edgecolor=bar_color,
            linewidths=2.2, zorder=5,
        )

    # Y-axis: parameter names
    ax.set_yticks(y_positions)
    ax.set_yticklabels([PARAM_LABELS[v] for v in var_names], fontsize=12)
    ax.set_ylim(y_baseline - 0.2, n - 0.4)

    # X-axis
    ax.set_xlabel("Parameter value", fontsize=12)
    ax.axvline(0, color="gray", linestyle=":", alpha=0.5, zorder=1)
    ax.grid(axis="x", alpha=0.25, linestyle="--")

    # Title
    ax.set_title(
        "Forest Plot: 95% Credible Intervals",
        fontsize=14, weight="bold", pad=15,
    )

    # Clean border styling
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# Main Workflow
def main() -> None:
    logger = setup_logging()

    logger.info("Loading trace.nc")
    idata = load_trace()

    logger.info("Building posterior summary table")
    summary_df = build_summary_table(idata)
    summary_path = RESULTS_DIR / POSTERIOR_TABLE_FILE
    summary_df.to_csv(summary_path, index=False)
    logger.info("Saved posterior table to %s", summary_path)

    print("\n=== Posterior Summary ===")
    print(summary_df.to_string(index=False))
    print()

    logger.info("Plotting posterior density")
    plot_posterior_density(idata, FIGURES_DIR / "posterior_density.png")

    logger.info("Plotting forest plot")
    plot_posterior_forest(idata, FIGURES_DIR / "posterior_forest.png")

    logger.info("Done.")


if __name__ == "__main__":
    main()
